packages:
  - "."
  - "workers/indexer"

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  tree-sitter: true
  tree-sitter-javascript: true
  tree-sitter-typescript: true

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - protobufjs
  - tree-sitter
  - tree-sitter-javascript
  - tree-sitter-typescript

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
